mapping = {
    'charge_pos_edge'     : 'histogram/config/charge_sharing/positive_edge',
    'charge_sum_enable'   : 'histogram/config/charge_sharing/sum_enable',
    'charge_neg_neighbour': 'histogram/config/charge_sharing/negative_neighbour',
    'charge_pos_adjust'   : 'histogram/config/charge_sharing/position_adjust',

    'thres_abs_low_default'  : 'histogram/config/thresholds/absolute/low',
    'thres_abs_high_default' : 'histogram/config/thresholds/absolute/high',
    'thres_low_neg_default'  : 'histogram/config/thresholds/low/neg',
    'thres_low_pos_default'  : 'histogram/config/thresholds/low/pos',
    'thres_main_neg_default' : 'histogram/config/thresholds/main/neg',
    'thres_main_pos_default' : 'histogram/config/thresholds/main/pos',

    'baseline_divide'      : 'histogram/config/baseline/divide',
    'baseline_dither'      : 'histogram/config/baseline/dither',
    'dark_tracking_enable' : 'acquisition/config/baseline/toggle',

    'auto_trigger_mode': 'histogram/config/clustering/auto_trig_mode',
    'cluster_mode'     : 'histogram/config/clustering/mode',
    # Cluster types: True/False
    'cluster_hoz'      : 'histogram/config/clustering/types/HOZ',
    'cluster_hoz_nl'   : 'histogram/config/clustering/types/HOZ_NL',
    'cluster_hoz_nr'   : 'histogram/config/clustering/types/HOZ_NR',
    'cluster_vert'     : 'histogram/config/clustering/types/VERT',
    'cluster_vert_na'  : 'histogram/config/clustering/types/VERT_NA',
    'cluster_vert_nb'  : 'histogram/config/clustering/types/VERT_NB',
    'cluster_diag1'    : 'histogram/config/clustering/types/DIAG1',
    'cluster_diag1nl'  : 'histogram/config/clustering/types/DIAG1NL',
    'cluster_diag1nr'  : 'histogram/config/clustering/types/DIAG1NR',
    'cluster_diag2'    : 'histogram/config/clustering/types/DIAG2',
    'cluster_diag2nl'  : 'histogram/config/clustering/types/DIAG2NL',
    'cluster_diag2nr'  : 'histogram/config/clustering/types/DIAG2NR',
    'cluster_quad'     : 'histogram/config/clustering/types/QUAD',
    'cluster_lone'     : 'histogram/config/clustering/types/LONE',
    'cluster_l1'       : 'histogram/config/clustering/types/L1',
    'cluster_l2'       : 'histogram/config/clustering/types/L2',
    'cluster_l3'       : 'histogram/config/clustering/types/L3',
    'cluster_l4'       : 'histogram/config/clustering/types/L4',

    # LOKI controls
    'highvoltage_enable'      : 'proxy/loki/application/HV/ENABLE',
    'highvoltage_target_bias' : 'proxy/loki/application/HV/target_bias',
    'peltier_enable'          : 'proxy/loki/application/peltier/enable',
    'peltier_setpoint'        : 'proxy/loki/application/peltier/temperature',
    'feedback_capacitance'    : 'proxy/loki/application/asic_settings/feedback_capacitance',
    'negative_dynamic_range'  : 'proxy/loki/application/asic_settings/negative_range_lowhigh',

    # File uploads
    'global_h5_filename'                : 'histogram/config/hdf_settings/filename',
    'global_h5_load'                    : 'histogram/config/hdf_settings/load',
    'bad_pixel_mask_filename'           : 'histogram/config/hist_format/bad_pixel_mask/filename',
    'bad_pixel_mask_load'               : 'histogram/config/hist_format/bad_pixel_mask/load',
    'bad_pixel_threshold_filename'      : 'histogram/config/thresholds/bad_pixel/filename',
    'bad_pixel_threshold_load'          : 'histogram/config/thresholds/bad_pixel/load',
    'charge_sharing_mc_filename'        : 'histogram/config/charge_sharing/mc_filename',
    'charge_sharing_mc_load'            : 'histogram/config/charge_sharing/mc_load',
    'charge_sharing_pos_filename'       : 'histogram/config/charge_sharing/pos_filename',
    'charge_sharing_pos_load'           : 'histogram/config/charge_sharing/pos_load',
    'charge_sharing_l3_filename'        : 'histogram/config/charge_sharing/l3_filename',
    'charge_sharing_l3_load'            : 'histogram/config/charge_sharing/l3_load',
    'linearity_correction_filename'     : 'histogram/config/linearity_correction/lin_filename',
    'linearity_correction_load'         : 'histogram/config/linearity_correction/lin_load',
    'linearity_correction_gain_filename': 'histogram/config/linearity_correction/gain_filename',
    'linearity_correction_gain_load'    : 'histogram/config/linearity_correction/gain_load'
}